# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  baseurl = "https://pjortiz.com/"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[fr]
  languageCode = "fr"
  baseurl = "https://pjortiz.fr/"
  contentDir = "content/fr"
[fr.marketing]
  google_analytics = "G-10ZMR236LE"
  google_tag_manager = ""
[[fr.menu.main]]
  name = "Accueil"
  url = "#about"
  weight = 1
[[fr.menu.main]]
   name = "Publications"
   url = "#featured"
   weight = 4
[[fr.menu.main]]
   name = "Présentations"
   url = "#talks"
   weight = 5
[[fr.menu.main]]
   name = "Projets"
   url = "#projects"
   weight = 6
[[fr.menu.main]]
   name = "Cours"
   url = "courses/"
   weight = 7
[[fr.menu.main]]
  name = "Contactez moi"
  url = "#contact"
  weight = 8
[[fr.menu.main]]
  name = "CV"
  url = "../files/cv_fr.pdf"
  weight = 9

# Additional Menus
[[fr.menu.mathdiscretes2019]]
  name = "Exercices"
  weight = 10
  identifier = "exercices"
[[fr.menu.mathdiscretes2019]]
  name = "Contrôle continu"
  weight = 20
  identifier = "control"

[[fr.menu.mathdiscretes]]
  name = "Notes TDs"
  weight = 10
  identifier = "notes"
[[fr.menu.mathdiscretes]]
  name = "Exercices TDs"
  weight = 20
  identifier = "exos"
# [[fr.menu.mathdiscretes]]
#   name = "Contrôle continu"
#   weight = 30
#   identifier = "control"

[es]
  languageCode = "es"
  baseurl = "https://pjortiz.co/"
  contentDir = "content/es"
[es.marketing]
  google_analytics = "G-3PS66SZZMH"
  google_tag_manager = ""
[[es.menu.main]]
  name = "Home"
  url = "#about"
  weight = 1
[[es.menu.main]]
   name = "Publicaciones"
   url = "#featured"
   weight = 2
[[es.menu.main]]
   name = "Presentaciones"
   url = "#talks"
   weight = 3
[[es.menu.main]]
   name = "Proyectos"
   url = "#projects"
   weight = 4
[[es.menu.main]]
  name = "Contacto"
  url = "#contact"
  weight = 6
[[es.menu.main]]
  name = "CV"
  url = "../files/cv.pdf"
  weight = 7
